import { motion } from "framer-motion";
import { Section } from "../components/ui";

export default function PrivacyTerms() {
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="pt-32 pb-20">
      <div className="max-w-[800px] mx-auto px-5">
        <div className="flex justify-center gap-6 mb-16 text-sm">
          <a href="#privacy" className="text-mint hover:underline">→ Jump to Privacy Policy</a>
          <a href="#terms" className="text-mint hover:underline">→ Jump to Terms & Conditions</a>
        </div>

        <section id="privacy" className="mb-20">
          <h1 className="font-syne font-bold text-4xl text-white mb-2">Privacy Policy</h1>
          <p className="text-[#707070] mb-10">Last updated: May 2026</p>
          
          <div className="space-y-8 text-[#E8E8E8] font-inter">
            <div>
              <h2 className="font-syne font-bold text-2xl text-white mb-4">1. Information We Collect</h2>
              <p className="text-[#707070] leading-relaxed">We collect information that you provide directly to us when you fill out a form, request an audit, or communicate with us. This may include your name, email address, phone number, and business details.</p>
            </div>
            <div>
              <h2 className="font-syne font-bold text-2xl text-white mb-4">2. How We Use Your Information</h2>
              <p className="text-[#707070] leading-relaxed">We use the information we collect to provide, maintain, and improve our services, to process transactions, and to communicate with you about products, services, and offers.</p>
            </div>
            <div>
              <h2 className="font-syne font-bold text-2xl text-white mb-4">3. Information Sharing</h2>
              <p className="text-[#707070] leading-relaxed">We do not sell or rent your personal information to third parties. We may share your information with trusted third-party service providers (such as Google Analytics and GoDaddy) strictly for the purpose of operating our website and business.</p>
            </div>
            <div>
              <h2 className="font-syne font-bold text-2xl text-white mb-4">4. Data Security & Your Rights</h2>
              <p className="text-[#707070] leading-relaxed">We implement reasonable security measures to protect your personal data. Depending on your location (e.g., GDPR, CCPA), you may have the right to access, correct, or delete your personal data.</p>
            </div>
            <div className="border-l-4 border-mint pl-6 py-4 bg-mint/5 rounded-r">
              <p className="text-mint text-sm">Full legal privacy content generated by Termly.io will be inserted here.</p>
            </div>
          </div>
        </section>

        <div className="w-full h-[1px] bg-mint/30 mb-20"></div>

        <section id="terms">
          <h2 className="font-syne font-bold text-4xl text-white mb-2">Terms & Conditions</h2>
          <p className="text-[#707070] mb-10">Last updated: May 2026</p>
          
          <div className="space-y-8 text-[#E8E8E8] font-inter">
            <div>
              <h3 className="font-syne font-bold text-2xl text-white mb-4">1. Services</h3>
              <p className="text-[#707070] leading-relaxed">RankBuildGrow agrees to provide digital marketing services as outlined in your specific project proposal or agreement.</p>
            </div>
            <div>
              <h3 className="font-syne font-bold text-2xl text-white mb-4">2. Payment Terms</h3>
              <p className="text-[#707070] leading-relaxed">Payment schedules are determined per project. Standard website development requires a 50% deposit upfront and 50% upon completion. Monthly retainers are billed on the 1st of each month.</p>
            </div>
            <div>
              <h3 className="font-syne font-bold text-2xl text-white mb-4">3. Intellectual Property</h3>
              <p className="text-[#707070] leading-relaxed">Upon final payment, all rights to the finished website design and content are transferred to the client. RankBuildGrow retains the right to display the work in our portfolio.</p>
            </div>
            <div>
              <h3 className="font-syne font-bold text-2xl text-white mb-4">4. Limitation of Liability</h3>
              <p className="text-[#707070] leading-relaxed">RankBuildGrow shall not be liable for any indirect, incidental, or consequential damages resulting from the use of our services.</p>
            </div>
            <div className="border-l-4 border-mint pl-6 py-4 bg-mint/5 rounded-r">
              <p className="text-mint text-sm">Full Terms & Conditions content will be inserted here.</p>
            </div>
          </div>
        </section>
      </div>
    </motion.div>
  );
}